### ISSUE TITLE
ICLR 2023 bundle

### ISSUE THREAD

**Issue by gisilvs** [pnkraemer/tueplots#104]
Would it be possible to add the style bundle for iclr 2023?

**Comment by pnkraemer** [comment]
Yes, it would definitely be possible to add the ICLR style!

Would you be willing to contribute a pull request?

We would need the respective functions in `fonts.py`, `fontsizes.py`, and `figsizes.py`. The existing content should be a decent point of reference. If you have any questions, please let me know :)

**Comment by pnkraemer** [comment]
Just to follow up: Is anyone interested in working on this? (@gisilvs, for example?) 

Otherwise, I will give it a shot in the next couple of days.
