### ISSUE TITLE
Related packages

### ISSUE THREAD

**Issue by pnkraemer** [pnkraemer/tueplots#20]
It could be useful to add information about related packages somewhere (to the readme?). This way we can mix and match (and also explain what we are doing differently)

There are for instance:
* Seaborn: https://seaborn.pydata.org/index.html
* ProPlot: https://proplot.readthedocs.io/en/latest/cycles.html
* SciencePlots: https://github.com/garrettj403/SciencePlots

Any others?

**Comment by pnkraemer** [comment]
https://github.com/nschloe/matplotx

**Comment by philipphennig** [comment]
Nice!
