### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by philipphennig** [pnkraemer/tueplots#4]
Feature request:
I would like to propose to store the colors in `colors.py` not as a tuple, but as an `np.array`. 

Reasoning: 
I'm planning to add the entire Uni Tü color palette. If they're stored as np.arrays, that makes it easier to interpolate between colors, in particular to create lighter versions of existing colors.

**Comment by philipphennig** [comment]
Actually it would be nice to just have them as static `np.arrays`, not as functions, too. Saves a lot of typing.

**Comment by fsschneider** [comment]
I think it would be great if we could also define a default color palette.

We could also use the default of `matplotlib` or `seaborn`, but I would prefer a custom one. A custom color palette would make our plots look much more recognizable. I guess @philipphennig you would have a preference for main, second, third, ... colors?

**Comment by philipphennig** [comment]
I mean, the obvious choice is the Uni-TUE color palette. It works well for plots with up to three lines. But I realise that it may not be everyone's cup of tea. We could keep the default color palette as the default and offer the `unitue` palette as a replacement. 

For what it's worth, I'm not a fan of `seaborn`. It's too heavy-handed for my taste.

**Comment by pnkraemer** [comment]
thanks for the great inputs! :) 

The original reasoning behind using functions was that I dont really like a bunch of constants lying around the source. But I guess constants are more practical anyway -- let's see how far we get with that! 
The original reasoning behind using tuples was that this way, the source is dependency-free. However, if we depend on matplotlib anyway (which has a numpy dependency, too), there is no real reason to avoid numpy arrays. So yes, we can change them into arrays.

Regarding the color palette: I think it is a great idea to add color palettes. How about not adding _a_ default color palette, but a range of palettes so a user can choose freely without us imposing our tastes? I have some color cycles lying around (tue, probnum, tufte, etc.) which I can turn into rcParams inputs.

I suppose then it would make sense to branch out the color module:
color/
   rgb/    # for RGB constants
   cycles/  # for color cycles

from where on one can expand.

**Comment by pnkraemer** [comment]
See #5.

**Comment by philipphennig** [comment]
Ok, great! 

I think static constants are fine if they are within the namespace of the package. `Numpy` has `np.pi`, so  it can't be _that_ bad :)

**Comment by pnkraemer** [comment]
#13 introduces color constants.
