### ISSUE TITLE
_Inches_per_Point is inverted

### ISSUE THREAD

**Issue by philipphennig** [pnkraemer/tueplots#81]
The Variable `_INCHES_PER_POINT = 1.0 * 72.27` in line 5 of `figsizes.py` is the wrong way round. It should either be renamed to `_POINTS_PER_INCH` or be set to `1.0 / 72.27`.

**Comment by pnkraemer** [comment]
Good catch! That is indeed invalid.

Would you like to resolve it yourself in a pull request? I assume it will be a quick fix :)  If not, I can take care of this later.
